spring.application.name: book-service
server.servlet.context-path: /api/v1

spring:
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888

strategy:
  service: FEIGN_CLIENT
